package com.company.Models;

public enum TargetType {
    ENEMY_HERO,
    FRIEND_HERO,
    SQUARE_2,
    SQUARE_3,
    ENEMY_ROW,
    ENEMY_COLUMN,
    WHOLE_ENEMY,
    WHOLE_FRIEND,
    NEAR_ENEMYS_HERO,
    NEAR_FRIENDS_HERO,
    ENEMY_MINION,
    FRIEND_MINION,
    ENEMY_SOLDIER,
    FRIEND_SOLDIER,
    ONE_CELL,
    RANDOM_FRIEND_SOLDIER,
    RANDOM_ENEMY_SOLDIER,
    SELF,
    MELEE_SOLDIERS
}
